spring:
  application:
    name: applicationGateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: flight-service
          uri: lb://FLIGHTSERVICE
          predicates:
            - Path=/flight/**
          filters:
            - AuthenticationFilter

        - id: booking-service
          uri: lb://BOOKINGSERVICE
          predicates:
            - Path=/booking/**
          filters:
            - AuthenticationFilter

        - id: security-service
          uri: lb://SECURITYSERVICE
          predicates:
            - Path=/auth/**

server:
  port: 6060

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10